### ISSUE TITLE
Add rustfmt configuration?

### ISSUE THREAD

**Issue by c00t** [FloatyMonkey/slang-rs#3]
I forked this repository and going to use `autocxx` to generate the reflection api.

But this crate uses a different rustfmt configuration than mine (and the default), which makes it difficult for me to merge the changes upstream. Please consider adding rustfmt configuration or other auto-formatting (hooks or ci) methods.

btw, the bindings I'm going to add are:
```rust
    slang::ShaderReflection
    slang::ProgramLayout
    slang::TypeLayoutReflection
    slang::EntryPointReflection
    slang::VariableLayoutReflection
    slang::TypeParameterReflection
```

**Comment by laurooyen** [comment]
Hi, thanks for your interest in taking on this task.

Currently there’s no rustfmt configuration at all. I’ll make sure to add one asap.

Would autocxx be the best way to generate these bindings? In addition we already use bindgen and some manually written bindings in slang-sys. This becomes rather complex. I feel like there might be no other option indeed, just haven’t looked into it yet.

**Comment by c00t** [comment]
> Currently there’s no rustfmt configuration at all. I’ll make sure to add one asap.

Great!

> Would autocxx be the best way to generate these bindings?

To be honest, I'm not sure, but I've done most of the prototyping. Using `autocxx` results in a lot of `fn foo(self: Pin <&mut bar>,...)` functions due to semantic differences between Rust/C++😢. My current approach is to only use `autocxx` to generate reflection api related types and have it reference other pod types generated by `bindgen` :

```rust
// lib.rs reexport
pub use cxxbind::{
    EntryPointReflection, ProgramLayout, TypeLayoutReflection, TypeParameterReflection,
    TypeReflection, UserAttribute, VariableLayoutReflection, VariableReflection,
};
// cxxbind.rs
include_cpp! {
    #include "slang.h"
    // TODO: slang_ParameterCategory and SlangParameterCategory should be merged in upstream.
    extern_cpp_type!("SlangParameterCategory",crate::SlangParameterCategory)
    pod!("SlangParameterCategory")
    extern_cpp_type!("SlangStage",crate::SlangStage)
    pod!("SlangStage")
    extern_cpp_type!("SlangResourceShape",crate::SlangResourceShape)
    pod!("SlangResourceShape")
    extern_cpp_type!("SlangResourceAccess",crate::SlangResourceAccess)
    pod!("SlangResourceAccess")
    extern_cpp_type!("SlangMatrixLayoutMode",crate::SlangMatrixLayoutMode)
    pod!("SlangMatrixLayoutMode")
    extern_cpp_type!("slang::ParameterCategory",crate::slang_ParameterCategory)
    pod!("slang::ParameterCategory")
    extern_cpp_type!("slang::BindingType",crate::slang_BindingType)
    pod!("slang::BindingType")
    extern_cpp_type!("slang::LayoutRules",crate::slang_LayoutRules)
    pod!("slang::LayoutRules")
    extern_cpp_type!("SlangResult",crate::ResultCode)
    pod!("SlangResult")
    generate!("slang::ShaderReflection")
    generate!("slang::ProgramLayout")
    generate!("slang::TypeLayoutReflection")
    generate!("slang::EntryPointReflection")
    generate!("slang::VariableLayoutReflection")
    generate!("slang::VariableReflection")
    generate!("slang::UserAttribute")
    generate!("slang::TypeParameterReflection")
}
```
