### ISSUE TITLE
Move incorrect `add_ref` from `create_session` to `load_module`

### ISSUE THREAD

**Issue by c00t** [FloatyMonkey/slang-rs#4]
https://github.com/FloatyMonkey/slang-rs/blob/095c719ff86333abb2441c1200aa8f67f0d0cb33/src/lib.rs#L122-L124

After comparing with the C++ code, I realized that manually adding `add_ref` here does not solve the problem(ref count of `GlobalSession` and `Session` are still `1` when dropped). 

 In the following code,

https://github.com/FloatyMonkey/slang-rs/blob/095c719ff86333abb2441c1200aa8f67f0d0cb33/src/lib.rs#L149-L163

**Rust**

```rust
let module = vcall!(self, loadModule(name.as_ptr(), &mut diagnostics));
```

**C++**

```cpp
// hello-world.cpp
    ComPtr<slang::IModule> slangModule = nullptr;
    {
        ComPtr<slang::IBlob> diagnosticBlob;
        slangModule = session->loadModule("hello-world", diagnosticBlob.writeRef());
        diagnoseIfNeeded(diagnosticBlob);
        if (!slangModule)
            return -1;
    }
// in slang-com-ptr.h
template <typename T>
T* ComPtr<T>::operator=(T* ptr)
{
	if (ptr) ((Ptr)ptr)->addRef();
	if (m_ptr) ((Ptr)m_ptr)->release();
	m_ptr = ptr;
	return m_ptr;
}
```

In C++, assignment results in an increase in ref count, which is not implemented in Rust. moving the manual `add_ref` to `load_module` solves the problem.

```rust
    pub fn load_module(&self, name: &str) -> Result<Module> {
        let name = CString::new(name).unwrap();
        let mut diagnostics = null_mut();

        let module = vcall!(self, loadModule(name.as_ptr(), &mut diagnostics));

        if module.is_null() {
            let blob = Blob(IUnknown::new(
                std::ptr::NonNull::new(diagnostics as *mut _).unwrap(),
            ));
            let error = std::str::from_utf8(blob.as_slice()).unwrap().to_string();
            return Err(anyhow!("{}", error));
        } else {
            let module = Module(IUnknown::new(
                std::ptr::NonNull::new(module as *mut _).unwrap(),
            ));
            unsafe { (module.as_unknown().vtable().ISlangUnknown_addRef)(module.as_raw()) };
            Ok(module)
        }
    }
```

With this modification, ref count of `GlobalSession` and `Session` after destruction become 0 (same as c++).

**Comment by laurooyen** [comment]
Great catch, and well explained! I'll push a fix for this.

In the future I'd like to add some internal helper functions to create IUnknowns and derivatives.
Right now there's a lot of repetition and without a better solution this issue will certainly pop up again.
